name: Setup Poetry Environment
description: Install Python and Poetry with caching for reproducible builds

inputs:
  python-version:
    description: Python version to use
    default: "3.12"
  poetry-version:
    description: Poetry version to install
    default: "1.8.3"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: Install Poetry
      shell: bash
      run: |
        pip install --upgrade pip
        pip install poetry==${{ inputs.poetry-version }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Poetry installation
      shell: bash
      run: |
        echo "Poetry version check:"
        which poetry || echo "❌ Poetry not found in PATH!"
        poetry --version || echo "⚠️ Poetry installation failed!"

    - name: Cache virtual environments
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ inputs.poetry-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
